"""
Phase 2 Runnable Demonstration Script.
Demonstrates telemetry collection, time-series feature extraction, Pandas DataFrame generation, and seed determinism.
"""

from src.simulation.engine import NetworkXEngine
from src.simulation.traffic import DeterministicTrafficGenerator
from src.telemetry.collector import TelemetryCollector
from src.telemetry.features import FeatureExtractor


def run_phase2_demo(seed: int = 42):
    print("=" * 80)
    print(f" PHASE 2 DEMO: Telemetry Collection & Feature Engineering (Seed: {seed})")
    print("=" * 80)

    # 1. Initialize Engine & Collector
    engine = NetworkXEngine(seed=seed)
    collector = TelemetryCollector()
    extractor = FeatureExtractor()

    # 2. Inject Deterministic Flows
    traffic_gen = DeterministicTrafficGenerator(seed=seed)
    flows = traffic_gen.generate_fixed_flow_set()

    # Add overload flow to trigger congestion & drop metrics
    overload_flow = traffic_gen.generate_random_flows(
        count=1,
        host_nodes=["H1", "H3"],
        min_demand_mbps=600.0,
        max_demand_mbps=600.0
    )[0]
    overload_flow.flow_id = "F4_OVERLOAD_600M"
    flows.append(overload_flow)

    for flow in flows:
        engine.add_flow(flow)

    # 3. Simulate 5 Ticks and Collect Snapshots
    print("\n[1] Collecting Telemetry Snapshots over 5 Ticks...")
    for _ in range(5):
        snapshot = engine.step()
        collector.collect(snapshot)

    print(f"    - Collected {len(collector.get_history())} Telemetry Snapshots.")

    # 4. Extract Feature DataFrame
    print("\n[2] Extracting ML-Ready Tabular Feature DataFrame...")
    df = extractor.to_dataframe(collector.get_history())

    print(f"    - Dataset Shape: {df.shape} (Rows: {df.shape[0]}, Columns: {df.shape[1]})")
    print("\n[3] Feature Columns Schema:")
    for col in df.columns:
        print(f"      - {col:<20} ({df[col].dtype})")

    # 5. Show Sample Time-Series Link Features (for congested link S1->S3 across ticks)
    print("\n[4] Time-Series Progression for Link 'S1->S3' across Ticks:")
    print("-" * 85)
    s1_s3_df = df[df["link_id"] == "S1->S3"][["tick", "current_load_mbps", "utilization", "prev_utilization", "delta_utilization", "is_congested"]]
    print(s1_s3_df.to_string(index=False))
    print("-" * 85)

    print("\n[5] First 10 Feature Rows Sample:")
    print("-" * 85)
    print(df[["tick", "link_id", "utilization", "delta_utilization", "total_bytes", "is_congested"]].head(10).to_string(index=False))
    print("-" * 85)

    return df


def verify_feature_determinism():
    print("=" * 80)
    print(" VERIFYING FEATURE EXTRACTION DETERMINISM (Seed 42 Run A vs Run B)")
    print("=" * 80)
    df_a = run_phase2_demo(seed=42)
    df_b = run_phase2_demo(seed=42)

    # Check exact equality of DataFrames
    equals = df_a.equals(df_b)
    assert equals, "Determinism failure: DataFrames generated by Run A and Run B differ!"
    print(">>> SUCCESS: Feature DataFrames from Run A and Run B match 100% identically! Determinism Verified.\n")


if __name__ == "__main__":
    verify_feature_determinism()
