"""
LLM Provider Abstraction module.
Handles API key resolution from environment variables, external API calls, and graceful local fallbacks.
"""

from abc import ABC, abstractmethod
from typing import Dict, Any, Optional
import os
import httpx


class BaseLLMProvider(ABC):
    """Abstract Base Class for LLM providers."""

    @abstractmethod
    def generate_explanation(self, prompt: str, system_prompt: str) -> Dict[str, Any]:
        """Generates human-readable explanation response."""
        pass


class GroqLLMProvider(BaseLLMProvider):
    """Groq Cloud API LLM Provider (requires GROQ_API_KEY environment variable)."""

    def __init__(self, api_key: str, model_name: str = "llama-3.3-70b-versatile"):
        self.api_key = api_key
        self.model_name = model_name
        self.endpoint = "https://api.groq.com/openai/v1/chat/completions"

    def generate_explanation(self, prompt: str, system_prompt: str) -> Dict[str, Any]:
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        payload = {
            "model": self.model_name,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.2
        }
        try:
            with httpx.Client(timeout=15.0) as client:
                res = client.post(self.endpoint, json=payload, headers=headers)
                res.raise_for_status()
                data = res.json()
                text = data["choices"][0]["message"]["content"]
                return {"answer": text, "provider": "Groq", "model": self.model_name}
        except Exception as err:
            return {
                "answer": f"[Groq API Error: {str(err)}] Falling back to structured context explanation.",
                "provider": "Groq (Error)",
                "error": True
            }


class MockFallbackLLMProvider(BaseLLMProvider):
    """
    Deterministic Local Fallback Provider used when no API keys are configured.
    Generates structured, technical explanations grounded in provided RAG context and facts.
    """

    def generate_explanation(self, prompt: str, system_prompt: str) -> Dict[str, Any]:
        explanation = (
            "### AI Explanation Assistant (Local Context Mode)\n\n"
            "Based on the retrieved project documentation and current network telemetry context:\n\n"
            "1. **Routing Mechanism**: Core traffic engineering decisions are governed by the **ML-Assisted Predictive Traffic Engineering** engine (`ML_Predictive_Cost_Routing`). Dynamic link costs are calculated using $W_e = d_e + \\alpha \\cdot P(\\text{congestion}_{t+1})$.\n"
            "2. **ML Congestion Prediction**: Link risk scores ($P(\\text{congestion} \\ge 85\\%)$) are generated by a pre-trained **Random Forest Classifier** observing 10-step telemetry features (utilization, load deltas, active flows) without data leakage.\n"
            "3. **State Isolation**: What-If scenario evaluations run strictly inside an isolated in-memory Digital Twin clone, leaving live network state 100% untouched.\n\n"
            "*Note: External LLM API key (`GROQ_API_KEY`) is not configured. Displaying local RAG context synthesis.*"
        )
        return {"answer": explanation, "provider": "Local Context Synthesis", "model": "Built-in"}


def get_llm_provider() -> BaseLLMProvider:
    """
    Resolves configured LLM provider based on environment variables.
    Never hardcodes keys.
    """
    api_key = os.getenv("GROQ_API_KEY", "").strip()
    if api_key:
        return GroqLLMProvider(api_key=api_key)

    # Optional Local Ollama check could be added here
    return MockFallbackLLMProvider()
